version: 2

updates:
  - package-ecosystem: github-actions
    directory: /.github
    schedule:
      interval: daily
      time: "10:00"
      timezone: Canada/Eastern
    reviewers:
      - Faire/detektors

  - package-ecosystem: gradle
    open-pull-requests-limit: 5
    directory: /
    schedule:
      interval: daily
      time: "10:00"
      timezone: Canada/Eastern
    reviewers:
      - Faire/detektors