name: Build and test
on: [ pull_request, push ]
jobs:
  JVM-Run-Gradle-Check:
    name: Build and test
    runs-on: ubuntu-latest
    # Run if github push is main branch or pull request
    if: ${{ github.ref == 'refs/heads/main' || github.event_name == 'pull_request' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version-file: '.java-version'

      - name: Verify gradle wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
            cache-read-only: ${{ github.event_name == 'push' && github.ref != 'refs/heads/main' }}

      - name: Run checks
        run: |
          ./gradlew check --continue

      - name: Run Build Health
        run: |
          ./gradlew buildHealth --continue
          # if 'build-health-report.txt' is not empty, fail and echo the content
          if [ -s build/reports/dependency-analysis/build-health-report.txt ]; then
              echo "Build health report:"
              cat build/reports/dependency-analysis/build-health-report.txt
              exit 1
          fi
